import { Product, Solution, Experiment, EcosystemBranch, NavigationLink } from '@/types';

export const EDC_META = {
  name: 'EDC Media',
  legalName: 'EDC Media HQ',
  domain: 'https://edcmediahq.xyz',
  positioning: 'EDC Media builds intelligent software systems that turn ideas, information, and repetitive work into automated outcomes.',
  eyebrow: 'EDC MEDIA HQ / 2026',
  headline: 'BUILDING INTELLIGENT SYSTEMS.',
  subheadline: 'EDC Media builds AI software, intelligent automation, and systems designed to turn ideas into outcomes.',
  telemetry: {
    system: 'EDC SYSTEM CORE',
    status: 'ONLINE',
    mode: 'PRODUCTION ARCHITECTURE',
    pillars: ['BUILD', 'INTELLIGENCE', 'AUTOMATION'],
  },
};

export const PRODUCTS: Product[] = [
  {
    id: 'prod-01',
    number: '01',
    slug: 'conversion-engine',
    name: 'EDC Conversion Engine',
    tagline: 'AI-powered landing pages, conversion optimization, and experimentation.',
    category: 'CONVERSION / AI',
    status: 'PRODUCT',
    description: 'High-velocity conversion infrastructure that synthesizes behavioral signals and real-time market data to deploy optimized landing experiences.',
    pillar: 'BUILD',
    features: [
      'Autonomous copy generation tuned to intent cohorts',
      'Continuous multivariate split-testing matrix',
      'Real-time analytics and funnel anomaly detection',
      'Headless API deployment across edge networks',
    ],
    href: '/products/conversion-engine',
  },
  {
    id: 'prod-02',
    number: '02',
    slug: 'buildos',
    name: 'EDC BuildOS',
    tagline: 'Transforms product ideas into structured software specifications and build sequences.',
    category: 'SYSTEM / SPECIFICATION',
    status: 'INTERNAL SYSTEM',
    description: 'A cognitive engineering compiler that ingests rough product concepts and outputs verified software specifications, architectural diagrams, and step-by-step build plans.',
    pillar: 'BUILD',
    features: [
      'Five-word concept expansion into architectural schematics',
      'Production-grade schema and API endpoint generation',
      'Strict task-dependency DAG sequencing',
      'Integration-ready export for engineering teams',
    ],
    href: '/buildos',
  },
  {
    id: 'prod-03',
    number: '03',
    slug: 'jarvis',
    name: 'EDC JARVIS',
    tagline: 'Conversational AI command-center experience.',
    category: 'COMMAND INTERFACE',
    status: 'R&D',
    description: 'A contextual executive interface orchestrating cross-system workflows, real-time research synthesis, and unified operations through fluid voice and text dialog.',
    pillar: 'AUTOMATION',
    features: [
      'Multi-modal command compilation and execution',
      'Contextual long-term operational memory',
      'Cross-tool integration via secure API gateways',
      'Real-time situational intelligence briefings',
    ],
    href: '/products/jarvis',
  },
  {
    id: 'prod-04',
    number: '04',
    slug: 'audio-intelligence',
    name: 'EDC Audio Intelligence',
    tagline: 'Research and evidence transformed into intelligent audio experiences.',
    category: 'RESEARCH / AUDIO',
    status: 'PRODUCT',
    description: 'Converts complex written research, technical whitepapers, and dynamic intelligence feeds into natural, multi-voice synthesized briefings and audio products.',
    pillar: 'INTELLIGENCE',
    features: [
      'Algorithmic paper summarization and script extraction',
      'Naturalistic cadence and high-fidelity vocal synthesis',
      'Segmented chapterization with dynamic citations',
      'Podcast and executive audio digest publishing',
    ],
    href: '/products/audio-intelligence',
  },
];

export const SOLUTIONS: Solution[] = [
  {
    id: 'sol-01',
    number: '01',
    slug: 'get-more-customers',
    title: 'GET MORE CUSTOMERS',
    subtitle: 'Conversion, sales, and lead-generation systems.',
    category: 'GROWTH / ACQUISITION',
    description: 'Deploy intelligent conversion engines and automated outreach workflows that systematically capture, qualify, and convert high-intent prospective buyers.',
    targetOutcome: 'Maximize customer acquisition velocity with zero manual bottleneck.',
    relevantProducts: ['EDC Conversion Engine', 'SalesPilot'],
    href: '/solutions/get-more-customers',
  },
  {
    id: 'sol-02',
    number: '02',
    slug: 'automate-operations',
    title: 'AUTOMATE OPERATIONS',
    subtitle: 'AI employees and intelligent workflows.',
    category: 'EFFICIENCY / SCALING',
    description: 'Replace fragmented manual handoffs with resilient, autonomous agents capable of data reconciliation, routing, and operational decision-making.',
    targetOutcome: 'Eliminate repetitive operational overhead across enterprise processes.',
    relevantProducts: ['BusinessPilot', 'EDC JARVIS'],
    href: '/solutions/automate-operations',
  },
  {
    id: 'sol-03',
    number: '03',
    slug: 'build-a-product',
    title: 'BUILD A PRODUCT',
    subtitle: 'AI-native product infrastructure and development systems.',
    category: 'ENGINEERING / ACCELERATION',
    description: 'Leverage EDC software compilation tools to compress months of specification, systems design, and foundational scaffolding into rapid build sequences.',
    targetOutcome: 'Transform software concepts into verified production codebases in days.',
    relevantProducts: ['EDC BuildOS', 'EDC Labs'],
    href: '/solutions/build-a-product',
  },
  {
    id: 'sol-04',
    number: '04',
    slug: 'understand-your-market',
    title: 'UNDERSTAND YOUR MARKET',
    subtitle: 'Research, intelligence, and evidence systems.',
    category: 'INTELLIGENCE / EVIDENCE',
    description: 'Continuous monitoring and synthetic analysis engines that extract competitive signals, customer sentiment trends, and emergent technical patterns.',
    targetOutcome: 'Maintain real-time situational awareness with verified data backing.',
    relevantProducts: ['EDC Audio Intelligence', 'Signals Engine'],
    href: '/solutions/understand-your-market',
  },
];

export const EXPERIMENTS: Experiment[] = [
  {
    id: 'exp-001',
    number: '001',
    slug: 'autonomous-business-operator',
    title: 'AUTONOMOUS BUSINESS OPERATOR',
    category: 'AI / AUTOMATION',
    statusLabel: 'CONCEPT',
    description: 'Exploring autonomous multi-agent networks capable of managing continuous reconciliations, vendor ticketing, and routine administrative decisions with deterministic guardrails.',
    explorationGoals: [
      'Self-healing API orchestration across billing and logistics',
      'Audit-logged human escalation boundaries',
      'Predictive cash-flow anomaly detection',
    ],
    href: '/labs/autonomous-business-operator',
  },
  {
    id: 'exp-002',
    number: '002',
    slug: 'synthetic-research-synthesizer',
    title: 'SYNTHETIC RESEARCH SYNTHESIZER',
    category: 'INTELLIGENCE / COGNITION',
    statusLabel: 'EXPLORATION',
    description: 'Investigating real-time parsing of distributed academic repositories, patent filings, and market disclosures to detect non-obvious technological intersections.',
    explorationGoals: [
      'Automated semantic citation graph construction',
      'Hypothesis contradiction and consensus scoring',
      'Streaming executive executive synthesis generation',
    ],
    href: '/labs/synthetic-research-synthesizer',
  },
  {
    id: 'exp-003',
    number: '003',
    slug: 'multi-modal-workflow-compiler',
    title: 'MULTI-MODAL WORKFLOW COMPILER',
    category: 'COMPILATION / RUNTIME',
    statusLabel: 'CONCEPT',
    description: 'Prototyping zero-shot transpilation from natural user actions and conversational commands directly into typed, verifiable serverless execution pipelines.',
    explorationGoals: [
      'Visual diagram and wireframe interpretation to code AST',
      'Runtime constraint verification prior to state mutation',
      'Deterministic rollback mechanisms for AI-orchestrated APIs',
    ],
    href: '/labs/multi-modal-workflow-compiler',
  },
];

export const ECOSYSTEM_DATA: EcosystemBranch[] = [
  {
    name: 'BUILD',
    tagline: 'AI-Native Software & Infrastructure',
    description: 'Engineered platforms and frameworks designed to accelerate product inception and production deployment.',
    accent: '#5CE1E6',
    nodes: [
      {
        id: 'node-buildos',
        name: 'BuildOS',
        type: 'ENGINEERING COMPILER',
        description: 'Translates high-level product intent into verifiable technical blueprints and execution sequences.',
        status: 'INTERNAL CORE',
        href: '/buildos',
      },
      {
        id: 'node-products',
        name: 'Products',
        type: 'PRODUCTION SUITE',
        description: 'Stand-alone commercial software systems addressing conversion, audio intelligence, and workflow operations.',
        status: 'ACTIVE',
        href: '/products',
      },
      {
        id: 'node-labs',
        name: 'Labs',
        type: 'INNOVATION ENGINE',
        description: 'Advanced prototyping laboratory where emerging cognitive architectures are evaluated before productization.',
        status: 'CONTINUOUS',
        href: '/labs',
      },
    ],
  },
  {
    name: 'INTELLIGENCE',
    tagline: 'Information to Actionable Knowledge',
    description: 'Deep synthesis systems converting heterogeneous, high-volume inputs into clear, actionable intelligence.',
    accent: '#7C6CFF',
    nodes: [
      {
        id: 'node-audio-ai',
        name: 'Audio AI',
        type: 'SYNTHETIC AUDIO',
        description: 'Converts extensive research, analysis, and documents into executive-grade listening experiences.',
        status: 'PRODUCTION',
        href: '/products/audio-intelligence',
      },
      {
        id: 'node-research',
        name: 'Research',
        type: 'DEEP SYNTHESIS',
        description: 'Structured methodologies and algorithmic tools that extract signals from complex datasets.',
        status: 'ACTIVE',
        href: '/intelligence',
      },
      {
        id: 'node-signals',
        name: 'Signals',
        type: 'RADAR & FORECASTING',
        description: 'Continuous telemetry on technological, market, and user demand shifts for predictive positioning.',
        status: 'INTERNAL',
        href: '/intelligence#signals',
      },
    ],
  },
  {
    name: 'AUTOMATION',
    tagline: 'Autonomous Workflows & Execution',
    description: 'Cognitive systems that assume ownership of repetitive operational workloads with precision.',
    accent: '#5CE1E6',
    nodes: [
      {
        id: 'node-bizpilot',
        name: 'BusinessPilot',
        type: 'OPERATIONS SUITE',
        description: 'Autonomous orchestration of back-office workflows, cross-app reconciliations, and reporting routines.',
        status: 'SYSTEM',
        href: '/solutions/automate-operations',
      },
      {
        id: 'node-salespilot',
        name: 'SalesPilot',
        type: 'CONVERSION PIPELINE',
        description: 'Algorithmic prospect engagement, objection handling, and intent-driven lead maturation.',
        status: 'SYSTEM',
        href: '/solutions/get-more-customers',
      },
      {
        id: 'node-jarvis',
        name: 'JARVIS',
        type: 'COMMAND CENTER',
        description: 'Unified conversational agent acting as the command layer across the full EDC ecosystem.',
        status: 'R&D LABS',
        href: '/products/jarvis',
      },
    ],
  },
];

export const NAVIGATION_LINKS: NavigationLink[] = [
  { label: 'Products', href: '/products', description: 'AI software built by EDC' },
  { label: 'Solutions', href: '/solutions', description: 'Targeted systems by business objective' },
  { label: 'Labs', href: '/labs', badge: 'R&D', description: 'Experimental concepts and future explorations' },
  { label: 'Intelligence', href: '/intelligence', description: 'Research and signal synthesis systems' },
  { label: 'Company', href: '/about', description: 'Principles, architecture, and EDC mission' },
];

export const SECONDARY_LINKS: NavigationLink[] = [
  { label: 'BuildOS', href: '/buildos', badge: 'CORE', description: 'Idea-to-blueprint software compiler' },
  { label: 'Marketplace', href: '/marketplace', description: 'Connectors, workflows, and modules' },
];

export const UTILITY_LINKS: NavigationLink[] = [
  { label: 'About EDC', href: '/about' },
  { label: 'Contact', href: '/contact' },
  { label: 'Privacy Protocol', href: '/privacy' },
  { label: 'Terms of Access', href: '/terms' },
];
